services:
  # Service name
  app:
    build:
      context: . # Smart enough to search for the Dockerfile inside the working directory
      target: development
    container_name: test-container-dev
    volumes:
      # The dot(.) = ${PWD}
      - ./src:/app/src:ro
    # Variables defined in environment take priority over those in env_file
    environment:
      - NODE_ENV=development
