services:
  # Service name
  app:
    container_name: test-container
    build: . # Smart enough to search for the Dockerfile inside the working directory
    volumes:
      # The dot(.) = ${PWD}
      - ./src:/app/src:ro
    ports:
      - '3000:3000'
    env_file:
      - ./.env
